main/urls.py
from django.urls import path
from .views import HomeView,LoginView,LogoutView,EmployeeDetailView,AddEmployeeView,delete_employee,Scheduled,ScheduledDetailView,delete_scheduled,AddScheduledView,MessageDetailView,AddMessageView,delete_message,MessagesView,OutOfOrderView,AddOutOfOrderView,delete_out_of_order

urlpatterns = [

    path('',HomeView.as_view(),name='home'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LoginView.as_view(),name='logout'),
    # Employeelar uchun urllar
    path('employee_detail/<int:pk>',EmployeeDetailView.as_view(),name='employee_detail'),
    path('delete_employee/<int:pk>',delete_employee,name='delete_employee'),
    path('add_employee/',AddEmployeeView.as_view(),name='add_employee'),

# Scheduled Messsage lar uchun urllar
    path('schuduled_messages/',Scheduled.as_view(),name='scheduled_messages'),
    path('scheduled_message_detail/<int:pk>',ScheduledDetailView.as_view(),name='scheduled_message_detail'),
    path('add_scheduled_messages/',AddScheduledView.as_view(),name='add_scheduled_messages'),
    path('delete_scheduled_message/<int:pk>',delete_scheduled,name='delete_schedulet'),

# Message templatelar uchun urllar
    path('messages/',MessagesView.as_view(),name='messages'),
    path('message_detail/<int:pk>',MessageDetailView.as_view(),name='message_detail'),
    path('add_messages/',AddMessageView.as_view(),name='add_messages'),
    path('delete_message/<int:pk>',delete_message,name='delete_message'),

# Navbatdan tashqari messagelar uchun
    path('out_of_order/',OutOfOrderView.as_view(),name='out_of_order'),
    path('add_out_of_order/',AddOutOfOrderView.as_view(),name='add_out_of_order'),
    path('delete_out_of_order/<int:pk>',delete_out_of_order,name='delete_out_of_order'),
]

university/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.db import models

class Day(models.Model):
    DAY_CHOICES = [
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday ', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
    ]
    day_of_week = models.CharField(max_length=20, choices=DAY_CHOICES)

    def __str__(self) -> str:
        return self.day_of_week
    

class Positions(models.Model):
    title = models.CharField(max_length=256, unique=True)
    def __str__(self) -> str:
        return self.title

class Employees(models.Model):
    name = models.CharField(max_length=256)
    surname = models.CharField(max_length=256)
    position = models.ForeignKey(Positions, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15, unique=True)
    telegram = models.CharField(max_length=20, unique=True)

    def __str__(self) -> str:
        return self.name
    
    

class Messages(models.Model):
    title = models.CharField(max_length=100)
    info = models.TextField()

    def __str__(self) -> str:
        return self.title

class Message_rass(models.Model):
    employee = models.ManyToManyField(Employees, blank=True)
    template = models.ForeignKey(Messages,on_delete=models.CASCADE,null=True, blank=True)
    position = models.ManyToManyField(Positions, blank=True)
    day_of_week = models.ManyToManyField(Day,blank=True)
    time = models.CharField(max_length=5)
    class Meta:
        verbose_name_plural = "Schedule_messages"

    def __str__(self) -> str:
        return f"{self.position} {self.day_of_week} {self.template}"
    def get_employees(self):
        employees = self.employee.all()
        employee_name = []
        for employee in employees:
            employee_name.append(employee.name)
        return employee_name

    def get_positions(self):
        positions = self.position.all()
        position_title = []
        for position in positions:
            position_title.append(position.title)
        return position_title

    def get_day_of_week(self):
        days = self.day_of_week.all()
        days_title = []
        for day in days:
            days_title.append(day.day_of_week)
        return days_title




class Out_of_order(models.Model):
    employee = models.ManyToManyField(Employees, blank=True)
    template = models.ForeignKey(Messages,on_delete=models.CASCADE,null=True, blank=True)
    message = models.TextField()
    position = models.ManyToManyField(Positions, blank=True)
    def get_employees(self):
        employees = self.employee.all()
        employee_name = []
        for employee in employees:
            employee_name.append(employee.name)
        return employee_name

    def get_positions(self):
        positions = self.position.all()
        position_title = []
        for position in positions:
            position_title.append(position.title) 
        return position_title

templates/index.html
{% include 'wrapper.html' %}

{% block content %}
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
           
                <div class="navbar-nav align-items-center ms-auto">
                        <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-user me-lg-2" aria-hidden="true"></i>
                            <span class="d-none d-lg-inline-flex">{{ admin }}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="/logout" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->



            <!-- Recent Sales Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Employees &nbsp &nbsp &nbsp &nbsp &nbsp<a href="/add_employee/"><i class="fa fa-plus-square" aria-hidden="true" style="font-size: 20px;"></i></a></h6>
                        
                        <form method="post">
                            {% csrf_token %}
                       <select style="border: none; background-color: #191C24; color: white;" name="selected_option">
                        <option value="none" disabled selected  >Roles</option>
                        {% for i in positions %}
                        <option value="{{ i.title }}">{{ i.title }}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" class="btn btn-sm btn-primary me-lg-3">Sorting</button>
                    </form>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0">
                            <thead>
                                <tr class="text-white">
                                    <th scope="col"><input class="form-check-input" type="checkbox" id="master_checkbox"></th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Surname</th>
                                    <th scope="col">Phone</th>
                                    <th scope="col">Telegram</th>
                                    <th scope="col">Position</th>
                                    <th scope="col">Detail</th>
                                </tr>
                                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

                                <script>
                                    $(document).ready(function() {
                                        // Barcha checkboxlarni tekshirish
                                        $('#master_checkbox').change(function() {
                                            // Master checkbox holatini olish
                                            var masterChecked = $(this).prop('checked');
                                            // Barcha boshqa checkboxlarni master checkbox holatiga moslash
                                            $('.other_checkbox').prop('checked', masterChecked);
                                        });
                                    });
                                </script>
                            </thead>
                            <tbody>
                                {% for employee in employees %}
                                <tr>
                                    <td><input class="form-check-input other_checkbox" type="checkbox"></td>
                                    <td>{{ employee.name }}</td>
                                    <td>{{ employee.surname }}</td>
                                    <td>{{ employee.phone }}</td>
                                    <td>{{ employee.telegram }}</td>
                                    <td>{{ employee.position }}</td>
                                    <td class="d-flex align-items-center justify-content-between"><a class="btn btn-sm btn-primary" style="width: 50%;" href="/employee_detail/{{ employee.id }}">Detail</a>
                                    <a href="/delete_employee/{{ employee.id }}"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Recent Sales End -->


         
        </div>


{% endblock content %}

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>DarkPan - Bootstrap 5 Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet"> 
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="/static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="/static/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/static/css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
 


        <!-- Sign In Start -->
        <div class="container-fluid">
            <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
                <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
                    <div class="bg-secondary rounded p-4 p-sm-5 my-4 mx-3">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                            <a href="index.html" class="">
                                <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>University Reminder</h3>
                            </a>
                            <h3>Sign In</h3>
                        </div>
                        <form action="" method="post">
                            {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="username" class="form-control" id="floatingInput" placeholder="palonchi" name="username">
                            <label for="floatingInput">Username</label>
                        </div>
                        <div class="form-floating mb-4">
                            <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password">
                            <label for="floatingPassword">Password</label>
                        </div>
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">Check me out</label>
                            </div>
                            <a href="">Forgot Password</a>
                        </div>
                        <button type="submit" class="btn btn-primary py-3 w-100 mb-4">Sign In</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Sign In End -->
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/chart/chart.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>

templates/message_templates.html
{% include 'wrapper.html' %}

{% block content %}
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
          
                <div class="navbar-nav align-items-center ms-auto">
                        <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-user me-lg-2" aria-hidden="true"></i>
                            <span class="d-none d-lg-inline-flex">{{ admin }}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="/logout" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->



            <!-- Recent Sales Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Message templates &nbsp &nbsp &nbsp &nbsp &nbsp<a href="/add_messages/"><i class="fa fa-plus-square" aria-hidden="true" style="font-size: 20px;"></i></a></h6>
                        
                      
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0" >
                            <thead>
                                <tr class="text-white">
                                    <th scope="col"><input class="form-check-input" type="checkbox" id="master_checkbox"></th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Info</th>
                                    <th scope="col">Detail</th>
                                </tr>
                                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

                                <script>
                                    $(document).ready(function() {
                                        // Barcha checkboxlarni tekshirish
                                        $('#master_checkbox').change(function() {
                                            // Master checkbox holatini olish
                                            var masterChecked = $(this).prop('checked');
                                            // Barcha boshqa checkboxlarni master checkbox holatiga moslash
                                            $('.other_checkbox').prop('checked', masterChecked);
                                        });
                                    });
                                </script>
                            </thead>
                            <tbody>
                                {% for i in messages %}
                                <tr >
                                    <td><input class="form-check-input other_checkbox" type="checkbox"></td>
                                    <td>{{ i.title }}</td>
                                    <td>{{ i.info }}</td>
                                    <td class="d-flex align-items-center justify-content-between"><a class="btn btn-sm btn-primary"  href="/message_detail/{{ i.id }}">Detail</a>
                                    <a href="/delete_message/{{ i.id }}"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Recent Sales End -->


         
        </div>


{% endblock content %}

templates/out_of_order.html
{% include 'wrapper.html' %}

{% block content %}
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
         
                <div class="navbar-nav align-items-center ms-auto">
                        <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-user me-lg-2" aria-hidden="true"></i>
                            <span class="d-none d-lg-inline-flex">{{ admin }}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="/logout" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->



            <!-- Recent Sales Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Out of order Messages &nbsp &nbsp &nbsp &nbsp &nbsp<a href="/add_out_of_order/"><i class="fa fa-plus-square" aria-hidden="true" style="font-size: 20px;"></i></a></h6>
                        
                      
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0" >
                            <thead>
                                <tr class="text-white">
                                    <th scope="col"><input class="form-check-input" type="checkbox" id="master_checkbox"></th>
                                    <th scope="col">Employees</th>
                                    <th scope="col">Message Template or message</th>
                                    <th scope="col">Positions</th>
                                    <th scope="col">Detail</th>

                                </tr>
                                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

                                <script>
                                    $(document).ready(function() {
                                        // Barcha checkboxlarni tekshirish
                                        $('#master_checkbox').change(function() {
                                            // Master checkbox holatini olish
                                            var masterChecked = $(this).prop('checked');
                                            // Barcha boshqa checkboxlarni master checkbox holatiga moslash
                                            $('.other_checkbox').prop('checked', masterChecked);
                                        });
                                    });
                                </script>
                            </thead>
                            <tbody>
                                {% for i in messages %}
                                <tr >
                                    <td><input class="form-check-input other_checkbox" type="checkbox"></td>
                                    <td>{{ i.get_employees }}</td>
                                    <td>{{ i.template }}</td>
                                    <td>{{ i.get_positions }}</td>
                                    <td><a href="/delete_out_of_order/{{ i.id }}"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Recent Sales End -->


         
        </div>


{% endblock content %}

templates/scheduled_messages.html
{% include 'wrapper.html' %}

{% block content %}
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
               
                <div class="navbar-nav align-items-center ms-auto">
                        <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-user me-lg-2" aria-hidden="true"></i>
                            <span class="d-none d-lg-inline-flex">{{ admin }}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="/logout" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->



            <!-- Recent Sales Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Scheduled Messages &nbsp &nbsp &nbsp &nbsp &nbsp<a href="/add_scheduled_messages/"><i class="fa fa-plus-square" aria-hidden="true" style="font-size: 20px;"></i></a></h6>
                        
                      
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0" >
                            <thead>
                                <tr class="text-white">
                                    <th scope="col"><input class="form-check-input" type="checkbox" id="master_checkbox"></th>
                                    <th scope="col">Employees</th>
                                    <th scope="col">Message Template</th>
                                    <th scope="col">Positions</th>
                                    <th scope="col">Day of the week</th>
                                    <th scope="col">Time</th>
                                    <th scope="col">Detail</th>
                                </tr>
                                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

                                <script>
                                    $(document).ready(function() {
                                        // Barcha checkboxlarni tekshirish
                                        $('#master_checkbox').change(function() {
                                            // Master checkbox holatini olish
                                            var masterChecked = $(this).prop('checked');
                                            // Barcha boshqa checkboxlarni master checkbox holatiga moslash
                                            $('.other_checkbox').prop('checked', masterChecked);
                                        });
                                    });
                                </script>
                            </thead>
                            <tbody>
                                {% for i in scheduled %}
                                <tr >
                                    <td><input class="form-check-input other_checkbox" type="checkbox"></td>
                                    <td>{{ i.get_employees }}</td>
                                    <td>{{ i.template }}</td>
                                    <td>{{ i.get_positions }}</td>
                                    <td>{{ i.get_day_of_week }}</td>
                                    <td>{{ i.time }}</td>
                                    <td class="d-flex align-items-center justify-content-between"><a class="btn btn-sm btn-primary"  href="/scheduled_message_detail/{{ i.id }}">Detail</a>
                                    <a href="/delete_scheduled_message/{{ i.id }}"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Recent Sales End -->


         
        </div>


{% endblock content %}

templates/update_employee.html
{% include 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <style>
        #id_name {
            margin-top: 10px;
            margin-bottom: 30px;
            color: white;

        }
        #id_surname {
            margin-top: 10px;
            margin-bottom: 30px;
            color: white;

        }
        #id_position {
            margin-top: 10px;
            margin-bottom: 30px;
            background-color: #191C24;
            color: white;

        }
        #id_phone {
            margin-top: 10px;
            margin-bottom: 30px;
            color: white;

        }
        #id_tg_id {
            margin-top: 10px;
            margin-bottom: 30px;
            color: white;

        }
    </style>
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
                <form class="d-none d-md-flex ms-1" method="post">

                    <input class="form-control bg-dark border-0" type="search" placeholder="Search">
                    <button type="submit " class="btn btn-sm btn-primary me-lg-3">Search </button>
                </form>
                <a href="/" class="btn btn-sm btn-warning me-lg-3">Reset </a>
                <div class="navbar-nav align-items-center ms-auto">
                        <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-user me-lg-2" aria-hidden="true"></i>
                            <span class="d-none d-lg-inline-flex">{{ admin }}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="/logout" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
            <div class="forform" style="width: 95%;   background-color: #191C24; margin: 50px auto; box-sizing: border-box; padding: 50px;">
                {% load crispy_forms_tags %}
            <form action="" method="post" style="width: 50%; margin: 50px auto;  padding: 20px; box-sizing: border-box;color: white;">
                {% csrf_token %}
                
                {{ form|crispy}}

                <button class="btn btn-success" type="submit">
                    Submit
                </button>
            </form>
           
        </div>


            
{% endblock content %}